version: '3'

services:
  app:
    build: .
    container_name: fast-app
    network_mode: host
    command: bash -c "uvicorn main:app"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated
